### PR TITLE
Yuml Class Diagram URL Fixes #1725

### LINKED ISSUE #1725: Download option at Yuml Class Diagram does not provide a proper return back in UmpleOnline
## Summary

Within the UmpleOnline, the users can generate the Yuml class diagram based on the modeling language. In a sample scenario, a user can create a model, generate the Yuml class diagram, and download it.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
image
2. Under the "Generate" section, select the target programming language as "Yuml Class Diagram".  Click "Generate It".
image
3. Scroll a bit down and click on the "Download the PNG file for the image" linked text URL.
image
4. The system loads the diagram in PNG format.
image
5. Now, there is no system-generated BACK button to go back to the previous page. The only option to go back is to click on the browser BACK button. If the user clicks on the browser back button, the system is reset to an empty page. All the previous changes are deleted.
image

## Expected Feature

The system should do any of the following-
1. Open the PNG image in a separate window.
2. Upon clicking on the browser back button, the system should return to the previously saved page.

### PR DESCRIPTION
**Pull request by Svetlana154**
Fixed the Yuml Class Diagram URL issue so that the links are opened on a new page

### CODE REVIEW

File: umpleonline/scripts/compiler.php [hunk 1]
```diff
@@ -532,18 +532,18 @@
...
+        $dltext = "&nbsp;<a target=\"YmlImage\" href=\"$imglink\">Download the PNG file for the image</a>&nbsp;<br/>
       <img src=\"$imglink\"\>";
       }
       else
       {
         // could not generate either because of Python problem
         // or the yuml server not delivering because it doesn't like automated systems
         $yumltxt = file_get_contents($thedir."/yuml.txt");        
-        $dltext = "&nbsp;<a target=\"yumlimg\" href=\"http://yuml.me/diagram/plain/class/".$yumltxt.".php\"> Click on this link to display the png in a different Tab (yuml.me doesn't like automated systems generating their images)</a>&nbsp;";
+        $dltext = "<a target=\"YmlImage\" target=\"yumlimg\" href=\"http://yuml.me/diagram/plain/class/".$yumltxt.".php\">Click on this link to display the png in a different Tab (yuml.me doesn't like automated systems generating their images)</a>&nbsp;";
```
Comment (TimLethbridge) [inline umpleonline/scripts/compiler.php]: The target= seems here twice (it is OK above, but it is here twice)

**Review by TimLethbridge — CHANGES_REQUESTED** [review]

**Review by TimLethbridge — APPROVED** [review]
